"""Build and atomically finalize trace-only RWD NWB outputs."""

from __future__ import annotations

import json
import os
from collections.abc import Callable
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
from hdmf.backends.hdf5.h5_utils import H5DataIO
from ndx_fiber_photometry import (
    FiberPhotometry,
    FiberPhotometryIndicators,
    FiberPhotometryResponseSeries,
    FiberPhotometryTable,
)
from ndx_ophys_devices import (
    ExcitationSource,
    ExcitationSourceModel,
    FiberInsertion,
    Indicator,
    OpticalFiber,
    OpticalFiberModel,
    Photodetector,
    PhotodetectorModel,
)
from nwbinspector import Importance, inspect_nwbfile
from pynwb import NWBHDF5IO, NWBFile, TimeSeries, validate
from pynwb.epoch import TimeIntervals
from pynwb.file import Subject

from driftless_photometry import __version__
from driftless_photometry.config import ROIConfig, RWDSourceConfig, SessionConfig
from driftless_photometry.diagnostics import FinalizationProgress, FinalizationStage
from driftless_photometry.provenance import (
    NWB_RUNTIME_PROVENANCE_SCRATCH_NAME,
    capture_runtime_provenance,
)
from driftless_photometry.rwd import (
    RWD_PROTOCOL_VERSION,
    RWDNormalizedSession,
    RWDSessionData,
    normalize_rwd_session,
)
from driftless_photometry.settings import NWB_SETTINGS_SCRATCH_NAME, settings_json

from .nwb import _make_events_table, _safe_filename

RWD_STREAM_METADATA_SCRATCH_NAME = "driftless_rwd_stream_metadata_json"


@dataclass(frozen=True, slots=True)
class RWDNWBWriteReport:
    """Validation and exact-count result for one RWD fiber/animal NWB."""

    path: Path
    pynwb_validation_errors: tuple[str, ...]
    inspector_messages: tuple[str, ...]
    stream_record_count: int
    trace_sample_count: int
    named_event_count: int


def _validate_inputs(config: SessionConfig, data: RWDSessionData) -> RWDNormalizedSession:
    if not isinstance(config.source, RWDSourceConfig):
        raise ValueError("RWD NWB finalizer requires an RWD acquisition source")
    if data.received_records and data.stream_metadata is None:
        raise ValueError("RWD stream metadata is required when records are present")
    return normalize_rwd_session(config, data)


def _create_nwbfile(config: SessionConfig, roi: ROIConfig, data: RWDSessionData) -> NWBFile:
    roi_session_id = f"{config.session_id}__{roi.fiber_id}"
    nwbfile = NWBFile(
        session_description=config.session_description,
        identifier=roi_session_id,
        session_start_time=config.session_start_time,
        session_id=roi_session_id,
        experimenter=[config.experimenter],
        lab=config.lab,
        institution=config.institution,
        keywords=["fiber photometry", "RWD", "read-only stream", "NWB"],
        data_collection=(
            "Fluorescence values and named event edges streamed by RWD software. "
            "Driftless did not control or observe exposure timing, LED commands, camera "
            "frames, or raw detector samples for this source."
        ),
        subject=Subject(
            subject_id=roi.animal_id,
            age=roi.subject_age,
            sex=roi.subject_sex,
            description=(
                f"Animal assigned to {roi.fiber_id}; brain region: {roi.brain_region}; "
                f"sensor type: {roi.sensor_type}."
            ),
        ),
        source_script=(
            "NWB file generated by driftless_photometry.storage.rwd_nwb.write_rwd_session_nwbs"
        ),
        source_script_file_name="driftless_photometry/storage/rwd_nwb.py",
        was_generated_by=[["driftless-bundle-photometry", __version__]],
    )
    nwbfile.add_scratch(
        settings_json(config),
        name=NWB_SETTINGS_SCRATCH_NAME,
        description="Versioned complete Driftless settings used for this RWD recording.",
    )
    provenance = data.runtime_provenance or capture_runtime_provenance(
        adapter_name="rwd_read_only_stream",
        adapter_version="1",
        protocol_version=RWD_PROTOCOL_VERSION,
    )
    nwbfile.add_scratch(
        json.dumps(provenance.to_document(), indent=2, sort_keys=True) + "\n",
        name=NWB_RUNTIME_PROVENANCE_SCRATCH_NAME,
        description="Runtime and RWD adapter provenance used to finalize this recording.",
    )
    source = config.source
    metadata = None if data.stream_metadata is None else asdict(data.stream_metadata)
    if metadata is not None:
        metadata["resolved_preamble_mode"] = data.stream_metadata.resolved_preamble_mode.value
        metadata["preamble"] = (
            None if data.stream_metadata.preamble is None else data.stream_metadata.preamble.hex()
        )
        metadata["machine_name"] = data.stream_metadata.machine_name.hex()
    nwbfile.add_scratch(
        json.dumps(
            {
                "protocol_version": RWD_PROTOCOL_VERSION,
                "timestamp_scale_s": source.timestamp_scale_s,
                "value_scale": source.value_scale,
                "stream_metadata": metadata,
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        name=RWD_STREAM_METADATA_SCRATCH_NAME,
        description=(
            "Exact RWD parser, scale, preamble, and machine identity metadata. The vendor "
            "timestamp unit is not documented and remains an explicit configured assumption."
        ),
    )
    return nwbfile


def _add_photometry_metadata_and_traces(
    nwbfile: NWBFile,
    config: SessionConfig,
    normalized: RWDNormalizedSession,
    roi: ROIConfig,
) -> None:
    source = config.source
    assert isinstance(source, RWDSourceConfig)
    mapping = next(
        mapping for mapping in source.channel_mappings if mapping.fiber_id == roi.fiber_id
    )
    detector_model = PhotodetectorModel(
        name="rwd_integrated_photodetector_model",
        manufacturer="RWD",
        model_number="not supplied",
        description=(
            "Detector integrated with the RWD fiber-photometry system; detector model, "
            "gain, filter, and ADC details were not supplied by the streaming protocol."
        ),
        detector_type="integrated detector; type not supplied",
        wavelength_range_in_nm=[float("nan"), float("nan")],
        gain=float("nan"),
        gain_unit="not supplied",
    )
    nwbfile.add_device_model(detector_model)
    detector = Photodetector(
        name="rwd_integrated_photodetector",
        description="RWD detector represented by vendor-processed streamed values.",
        serial_number="not supplied",
        model=detector_model,
    )
    nwbfile.add_device(detector)

    fiber_model = OpticalFiberModel(
        name="rwd_optical_fiber_model_not_supplied",
        manufacturer="not supplied",
        description="RWD-connected optical fiber; construction metadata was not supplied.",
        numerical_aperture=float("nan"),
    )
    nwbfile.add_device_model(fiber_model)
    optical_fiber = OpticalFiber(
        name=f"optical_{roi.fiber_id}",
        description=f"Optical fiber mapped from RWD device channel {mapping.device_channel}.",
        model=fiber_model,
        fiber_insertion=FiberInsertion(name="fiber_insertion"),
    )
    nwbfile.add_device(optical_fiber)
    indicator = Indicator(
        name="indicator_01",
        label=roi.sensor_type,
        description="Sensor/indicator metadata supplied for this mapped fiber and animal.",
    )

    excitation_sources: dict[int, ExcitationSource] = {}
    for wavelength_nm in source.enabled_wavelengths_nm:
        source_model = ExcitationSourceModel(
            name=f"rwd_{wavelength_nm}_source_model",
            manufacturer="RWD",
            description=(
                f"Vendor-integrated source identified only as {wavelength_nm} nm by the "
                "RWD stream; model and optical-power metadata were not supplied."
            ),
            source_type="vendor-integrated source; type not supplied",
            excitation_mode="not supplied",
            wavelength_range_in_nm=[float(wavelength_nm), float(wavelength_nm)],
        )
        nwbfile.add_device_model(source_model)
        excitation_source = ExcitationSource(
            name=f"rwd_{wavelength_nm}_source",
            description=f"Exact {wavelength_nm} nm source identity reported by RWD.",
            model=source_model,
            exposure_time_in_s=float("nan"),
        )
        nwbfile.add_device(excitation_source)
        excitation_sources[wavelength_nm] = excitation_source

    table = FiberPhotometryTable(
        name="fiber_photometry_table",
        description="One row per mapped RWD fiber and exact streamed wavelength.",
    )
    table.add_column(name="fiber_id", description="Stable Driftless fiber identifier.")
    table.add_column(name="rwd_device_channel", description="Exact RWD device-channel byte.")
    table.add_column(
        name="signal_role",
        description="Vendor-unclassified signal; no control/signal role was inferred.",
    )
    row_indices: dict[int, list[int]] = {}
    for row_index, wavelength_nm in enumerate(source.enabled_wavelengths_nm):
        table.add_row(
            location=roi.brain_region,
            excitation_wavelength_in_nm=float(wavelength_nm),
            emission_wavelength_in_nm=float("nan"),
            indicator=indicator,
            optical_fiber=optical_fiber,
            excitation_source=excitation_sources[wavelength_nm],
            photodetector=detector,
            fiber_id=roi.fiber_id,
            rwd_device_channel=mapping.device_channel,
            signal_role="vendor_unclassified",
            notes=(
                f"Animal {roi.animal_id}; RWD stream provides no camera geometry, emission "
                "wavelength, exposure duration, commanded power, or raw detector counts."
            ),
        )
        row_indices[wavelength_nm] = [row_index]

    nwbfile.add_lab_meta_data(
        FiberPhotometry(
            name="FiberPhotometry",
            fiber_photometry_table=table,
            fiber_photometry_indicators=FiberPhotometryIndicators(indicators=[indicator]),
        )
    )
    fiber_samples = [sample for sample in normalized.samples if sample.fiber_id == roi.fiber_id]
    for wavelength_nm in source.enabled_wavelengths_nm:
        wavelength_samples = [
            sample for sample in fiber_samples if int(sample.wavelength_nm) == wavelength_nm
        ]
        if not wavelength_samples:
            continue
        timestamps = np.asarray(
            [sample.timestamp_s for sample in wavelength_samples], dtype=np.float64
        )
        region = table.create_region(
            name="fiber_photometry_table_region",
            region=row_indices[wavelength_nm],
            description=f"The exact {wavelength_nm} nm RWD response column.",
        )
        nwbfile.add_acquisition(
            FiberPhotometryResponseSeries(
                name=f"rwd_fluorescence_{wavelength_nm}",
                description=(
                    "Vendor-processed fluorescence value after applying the persisted "
                    "RWD value_scale; this is not a raw camera or detector sample."
                ),
                data=H5DataIO(
                    np.asarray(
                        [[sample.scaled_value] for sample in wavelength_samples],
                        dtype=np.float64,
                    ),
                    compression="gzip",
                    compression_opts=1,
                    shuffle=True,
                ),
                unit="a.u.",
                timestamps=timestamps,
                fiber_photometry_table_region=region,
            )
        )
        nwbfile.add_acquisition(
            TimeSeries(
                name=f"rwd_raw_value_{wavelength_nm}",
                description=(
                    "Exact uint32 value from the RWD wire record before configured scaling."
                ),
                data=np.asarray(
                    [sample.raw_value for sample in wavelength_samples], dtype=np.uint32
                ),
                unit="RWD wire integer units",
                timestamps=timestamps,
            )
        )


def _add_events(
    nwbfile: NWBFile,
    data: RWDSessionData,
    normalized: RWDNormalizedSession,
    roi: ROIConfig,
    additional_system_events: tuple[str, ...],
) -> None:
    stream_records = _make_events_table(
        name="rwd_stream_records",
        description="Every parsed RWD record in exact wire order.",
        source_description="RWD TCP fluorescence/event byte stream.",
        columns=(
            ("wire_sequence", "Zero-based record order assigned by Driftless."),
            ("record_type", "fluorescence or event."),
            ("machine_name_hex", "Exact four machine-name bytes encoded as hexadecimal."),
            ("host_received_s", "Host monotonic receipt time retained as provenance."),
            ("device_channel", "RWD device channel, or -1 for a named event."),
            ("sample_count", "Number of present fluorescence wavelength slots."),
            ("wavelength_mask", "Reconstructed RWD wavelength-presence bit mask."),
        ),
    )
    for record in normalized.records:
        stream_records.add_row(
            timestamp=record.timestamp_s,
            wire_sequence=record.wire_sequence,
            record_type=record.record_type,
            machine_name_hex=record.machine_name.hex(),
            host_received_s=record.host_received_s,
            device_channel=record.device_channel,
            sample_count=record.sample_count,
            wavelength_mask=record.wavelength_mask,
        )
    nwbfile.add_events_table(stream_records)

    fluorescence = _make_events_table(
        name="rwd_fluorescence_samples",
        description="Exact trace samples for the mapped fiber represented by this file.",
        source_description="RWD TCP fluorescence records.",
        columns=(
            ("wire_sequence", "Parent RWD record order."),
            ("machine_name_hex", "Exact four machine-name bytes encoded as hexadecimal."),
            ("host_received_s", "Host monotonic receipt time retained as provenance."),
            ("device_channel", "Exact RWD device-channel byte."),
            ("fiber_id", "Stable configured Driftless fiber identifier."),
            ("wavelength_nm", "Exact RWD wavelength label: 410, 470, or 560 nm."),
            ("raw_timestamp_tick", "Exact uint32 timestamp from the wire record."),
            ("unwrapped_timestamp_tick", "Rollover-unwrapped RWD timestamp tick."),
            ("raw_value", "Exact uint32 vendor fluorescence value."),
            ("scaled_value", "Value after applying the persisted configured value_scale."),
        ),
    )
    fiber_samples = [sample for sample in normalized.samples if sample.fiber_id == roi.fiber_id]
    for sample in fiber_samples:
        fluorescence.add_row(
            timestamp=sample.timestamp_s,
            wire_sequence=sample.wire_sequence,
            machine_name_hex=sample.machine_name.hex(),
            host_received_s=sample.host_received_s,
            device_channel=sample.device_channel,
            fiber_id=sample.fiber_id,
            wavelength_nm=int(sample.wavelength_nm),
            raw_timestamp_tick=sample.raw_timestamp_tick,
            unwrapped_timestamp_tick=sample.unwrapped_timestamp_tick,
            raw_value=sample.raw_value,
            scaled_value=sample.scaled_value,
        )
    nwbfile.add_events_table(fluorescence)

    named_events = _make_events_table(
        name="rwd_named_events",
        description="Every RWD named event edge, copied into each independently useful file.",
        source_description="RWD TCP event records.",
        columns=(
            ("wire_sequence", "RWD record order."),
            ("machine_name_hex", "Exact four machine-name bytes encoded as hexadecimal."),
            ("host_received_s", "Host monotonic receipt time retained as provenance."),
            ("raw_timestamp_tick", "Exact uint32 timestamp from the wire record."),
            ("unwrapped_timestamp_tick", "Rollover-unwrapped RWD timestamp tick."),
            ("event_name", "Decoded printable ASCII event name."),
            ("event_name_hex", "Exact fixed 20-byte event-name field as hexadecimal."),
            ("status", "Exact RWD status byte: 0 ON, 1 OFF."),
            ("active", "True for ON and false for OFF."),
        ),
    )
    for event in normalized.events:
        named_events.add_row(
            timestamp=event.timestamp_s,
            wire_sequence=event.wire_sequence,
            machine_name_hex=event.machine_name.hex(),
            host_received_s=event.host_received_s,
            raw_timestamp_tick=event.raw_timestamp_tick,
            unwrapped_timestamp_tick=event.unwrapped_timestamp_tick,
            event_name=event.event_name,
            event_name_hex=event.event_name_raw.hex(),
            status=event.status,
            active=event.active,
        )
    nwbfile.add_events_table(named_events)

    stop_time = max((record.timestamp_s for record in normalized.records), default=0.0)
    system = _make_events_table(
        name="system_events",
        description="RWD bridge lifecycle, recovery, and fault events.",
        source_description="Driftless RWD bridge.",
        columns=(
            ("event", "Lifecycle or machine-readable fault classification."),
            ("detail", "Human-readable detail; empty for ordinary lifecycle events."),
        ),
    )
    system.add_row(timestamp=0.0, event="recording_started", detail="")
    system.add_row(timestamp=stop_time, event="recording_stopped", detail="")
    for event in data.system_events:
        system.add_row(timestamp=event.timestamp_s, event=event.event, detail=event.detail)
    for event in additional_system_events:
        system.add_row(timestamp=stop_time, event=event, detail="")
    nwbfile.add_events_table(system)

    if data.invalid_times:
        invalid_times = TimeIntervals(
            name="invalid_times",
            description="Continuous RWD session spans whose scientific validity is compromised.",
        )
        invalid_times.add_column(name="reason", description="Human-readable invalidity reason.")
        invalid_times.add_column(
            name="source_event", description="Fault/event that created the invalid span."
        )
        for interval in data.invalid_times:
            invalid_times.add_row(
                start_time=interval.start_time_s,
                stop_time=interval.stop_time_s,
                tags=(interval.source_event,),
                reason=interval.reason,
                source_event=interval.source_event,
            )
        nwbfile.add_time_intervals(invalid_times)


def _rwd_output_paths(config: SessionConfig, roi: ROIConfig) -> tuple[Path, Path]:
    stem = "__".join(
        (
            _safe_filename(config.session_id),
            _safe_filename(roi.animal_id),
            _safe_filename(roi.fiber_id),
        )
    )
    output_directory = config.output_directory.expanduser().resolve()
    return output_directory / f"{stem}.nwb", output_directory / f"{stem}.partial.nwb"


def _round_trip_verify(
    candidate_path: Path,
    config: SessionConfig,
    data: RWDSessionData,
    normalized: RWDNormalizedSession,
    roi: ROIConfig,
    additional_system_events: tuple[str, ...],
) -> None:
    source = config.source
    assert isinstance(source, RWDSourceConfig)
    expected_samples = [sample for sample in normalized.samples if sample.fiber_id == roi.fiber_id]
    with NWBHDF5IO(candidate_path, mode="r", load_namespaces=True) as io:
        nwbfile = io.read()
        if nwbfile.session_id != f"{config.session_id}__{roi.fiber_id}":
            raise RuntimeError("RWD NWB session identity mismatch")
        if nwbfile.subject is None or nwbfile.subject.subject_id != roi.animal_id:
            raise RuntimeError("RWD NWB subject identity mismatch")
        if NWB_SETTINGS_SCRATCH_NAME not in nwbfile.scratch:
            raise RuntimeError("RWD NWB settings snapshot is missing")
        if NWB_RUNTIME_PROVENANCE_SCRATCH_NAME not in nwbfile.scratch:
            raise RuntimeError("RWD NWB runtime provenance is missing")
        if RWD_STREAM_METADATA_SCRATCH_NAME not in nwbfile.scratch:
            raise RuntimeError("RWD NWB stream metadata is missing")
        if set(nwbfile.events) != {
            "rwd_stream_records",
            "rwd_fluorescence_samples",
            "rwd_named_events",
            "system_events",
        }:
            raise RuntimeError("RWD NWB contains missing or unexpected event tables")
        if len(nwbfile.events["rwd_stream_records"]) != len(normalized.records):
            raise RuntimeError("RWD NWB stream-record count mismatch")
        if len(nwbfile.events["rwd_fluorescence_samples"]) != len(expected_samples):
            raise RuntimeError("RWD NWB trace-sample count mismatch")
        if len(nwbfile.events["rwd_named_events"]) != len(normalized.events):
            raise RuntimeError("RWD NWB named-event count mismatch")
        expected_system_count = 2 + len(data.system_events) + len(additional_system_events)
        if len(nwbfile.events["system_events"]) != expected_system_count:
            raise RuntimeError("RWD NWB system-event count mismatch")
        if data.invalid_times:
            if "invalid_times" not in nwbfile.intervals:
                raise RuntimeError("RWD NWB invalid-time table is missing")
            if len(nwbfile.intervals["invalid_times"]) != len(data.invalid_times):
                raise RuntimeError("RWD NWB invalid-time count mismatch")
        elif "invalid_times" in nwbfile.intervals:
            raise RuntimeError("RWD NWB contains an unexpected invalid-time table")
        table = nwbfile.lab_meta_data["FiberPhotometry"].fiber_photometry_table
        wavelengths = table.to_dataframe()["excitation_wavelength_in_nm"].to_numpy()
        if not np.array_equal(wavelengths, np.asarray(source.enabled_wavelengths_nm)):
            raise RuntimeError("RWD NWB exact wavelength identity mismatch")
        for wavelength_nm in source.enabled_wavelengths_nm:
            samples = [
                sample for sample in expected_samples if int(sample.wavelength_nm) == wavelength_nm
            ]
            scaled_name = f"rwd_fluorescence_{wavelength_nm}"
            raw_name = f"rwd_raw_value_{wavelength_nm}"
            if not samples:
                if scaled_name in nwbfile.acquisition or raw_name in nwbfile.acquisition:
                    raise RuntimeError("RWD NWB contains an unexpected empty trace")
                continue
            scaled = nwbfile.acquisition[scaled_name]
            raw = nwbfile.acquisition[raw_name]
            if scaled.data.shape != (len(samples), 1):
                raise RuntimeError(f"RWD NWB trace shape mismatch for {wavelength_nm} nm")
            if not np.array_equal(
                scaled.data[:, 0], np.asarray([sample.scaled_value for sample in samples])
            ):
                raise RuntimeError(f"RWD NWB scaled values mismatch for {wavelength_nm} nm")
            if raw.data.dtype != np.dtype("uint32") or not np.array_equal(
                raw.data[:], np.asarray([sample.raw_value for sample in samples], dtype=np.uint32)
            ):
                raise RuntimeError(f"RWD NWB raw values mismatch for {wavelength_nm} nm")
            expected_timestamps = np.asarray([sample.timestamp_s for sample in samples])
            if not np.array_equal(scaled.timestamps[:], expected_timestamps):
                raise RuntimeError(f"RWD NWB timestamps mismatch for {wavelength_nm} nm")
        forbidden = {
            "camera_frames",
            "excitation_events",
            "ttl_edges",
            "dropped_frame_events",
        }
        if forbidden.intersection(nwbfile.events) or "camera_frames" in nwbfile.acquisition:
            raise RuntimeError("RWD NWB invents native camera/controller records")
        if nwbfile.stimulus:
            raise RuntimeError("RWD NWB invents commanded stimulus data")


def _validate_candidate(
    candidate_path: Path,
    final_path: Path,
    config: SessionConfig,
    data: RWDSessionData,
    normalized: RWDNormalizedSession,
    roi: ROIConfig,
    additional_system_events: tuple[str, ...],
) -> RWDNWBWriteReport:
    validation_errors = tuple(str(error) for error in validate(path=candidate_path))
    if validation_errors:
        raise RuntimeError("PyNWB validation failed: " + "; ".join(validation_errors))
    inspector_messages = tuple(
        str(message)
        for message in inspect_nwbfile(
            candidate_path,
            skip_validate=True,
            importance_threshold=Importance.CRITICAL,
            ignore=["check_data_orientation"],
        )
        if message is not None
    )
    if inspector_messages:
        raise RuntimeError("NWB Inspector found critical issues: " + "; ".join(inspector_messages))
    _round_trip_verify(
        candidate_path,
        config,
        data,
        normalized,
        roi,
        additional_system_events,
    )
    return RWDNWBWriteReport(
        path=final_path,
        pynwb_validation_errors=validation_errors,
        inspector_messages=inspector_messages,
        stream_record_count=len(normalized.records),
        trace_sample_count=sum(sample.fiber_id == roi.fiber_id for sample in normalized.samples),
        named_event_count=len(normalized.events),
    )


def _write_partial(
    config: SessionConfig,
    data: RWDSessionData,
    normalized: RWDNormalizedSession,
    roi_index: int,
    additional_system_events: tuple[str, ...],
    on_progress: Callable[[FinalizationProgress], None] | None,
) -> RWDNWBWriteReport:
    roi = config.enabled_rois[roi_index]
    final_path, partial_path = _rwd_output_paths(config, roi)
    if on_progress is not None:
        on_progress(
            FinalizationProgress(
                stage=FinalizationStage.WRITING,
                completed_roi_files=roi_index,
                total_roi_files=len(config.enabled_rois),
                fiber_id=roi.fiber_id,
            )
        )
    nwbfile = _create_nwbfile(config, roi, data)
    _add_photometry_metadata_and_traces(nwbfile, config, normalized, roi)
    _add_events(nwbfile, data, normalized, roi, additional_system_events)
    with NWBHDF5IO(partial_path, mode="w") as io:
        io.write(nwbfile, cache_spec=True)
    if on_progress is not None:
        on_progress(
            FinalizationProgress(
                stage=FinalizationStage.VALIDATING,
                completed_roi_files=roi_index,
                total_roi_files=len(config.enabled_rois),
                fiber_id=roi.fiber_id,
            )
        )
    return _validate_candidate(
        partial_path,
        final_path,
        config,
        data,
        normalized,
        roi,
        additional_system_events,
    )


def write_rwd_session_nwbs(
    config: SessionConfig,
    data: RWDSessionData,
    *,
    additional_system_events: tuple[str, ...] = (),
    on_progress: Callable[[FinalizationProgress], None] | None = None,
) -> tuple[RWDNWBWriteReport, ...]:
    """Write, validate, then atomically promote one trace-only NWB per mapped fiber."""

    normalized = _validate_inputs(config, data)
    output_directory = config.output_directory.expanduser().resolve()
    output_directory.mkdir(parents=True, exist_ok=True)
    paths = [_rwd_output_paths(config, roi) for roi in config.enabled_rois]
    collisions = [path for pair in paths for path in pair if path.exists()]
    if collisions:
        raise FileExistsError("RWD ROI output already exists: " + ", ".join(map(str, collisions)))
    if on_progress is not None:
        on_progress(
            FinalizationProgress(
                stage=FinalizationStage.PREPARING,
                completed_roi_files=0,
                total_roi_files=len(paths),
            )
        )
    reports = tuple(
        _write_partial(
            config,
            data,
            normalized,
            roi_index,
            additional_system_events,
            on_progress,
        )
        for roi_index in range(len(config.enabled_rois))
    )
    if on_progress is not None:
        on_progress(
            FinalizationProgress(
                stage=FinalizationStage.PROMOTING,
                completed_roi_files=0,
                total_roi_files=len(paths),
            )
        )
    for report, (_, partial_path) in zip(reports, paths, strict=True):
        os.replace(partial_path, report.path)
    if on_progress is not None:
        on_progress(
            FinalizationProgress(
                stage=FinalizationStage.COMPLETE,
                completed_roi_files=len(paths),
                total_roi_files=len(paths),
            )
        )
    return reports


def recover_or_resume_rwd_session_nwbs(
    config: SessionConfig,
    data: RWDSessionData,
    *,
    additional_system_events: tuple[str, ...] = (),
    on_progress: Callable[[FinalizationProgress], None] | None = None,
) -> tuple[tuple[RWDNWBWriteReport, ...], bool]:
    """Validate/reuse RWD candidates and resume interrupted all-fiber promotion."""

    normalized = _validate_inputs(config, data)
    output_directory = config.output_directory.expanduser().resolve()
    output_directory.mkdir(parents=True, exist_ok=True)
    paths = [_rwd_output_paths(config, roi) for roi in config.enabled_rois]
    reports: list[RWDNWBWriteReport] = []
    reused_existing = False
    for roi_index, (final_path, partial_path) in enumerate(paths):
        roi = config.enabled_rois[roi_index]
        if final_path.exists() and partial_path.exists():
            raise FileExistsError(
                f"both canonical and partial RWD outputs exist: {final_path}, {partial_path}"
            )
        candidate = final_path if final_path.exists() else partial_path
        if candidate.exists():
            reused_existing = True
            try:
                report = _validate_candidate(
                    candidate,
                    final_path,
                    config,
                    data,
                    normalized,
                    roi,
                    additional_system_events,
                )
            except Exception:
                if candidate == final_path:
                    raise
                candidate.unlink()
                report = _write_partial(
                    config,
                    data,
                    normalized,
                    roi_index,
                    additional_system_events,
                    on_progress,
                )
        else:
            report = _write_partial(
                config,
                data,
                normalized,
                roi_index,
                additional_system_events,
                on_progress,
            )
        reports.append(report)
    for report, (final_path, partial_path) in zip(reports, paths, strict=True):
        if not final_path.exists():
            os.replace(partial_path, report.path)
    if on_progress is not None:
        on_progress(
            FinalizationProgress(
                stage=FinalizationStage.COMPLETE,
                completed_roi_files=len(paths),
                total_roi_files=len(paths),
            )
        )
    return tuple(reports), reused_existing
