"""RWD read-only streaming contracts."""

from .capture import (
    RWDWireCaptureError,
    RWDWireCaptureInspection,
    RWDWireCaptureWriter,
    RWDWireChunk,
    RWDWireReplaySource,
    inspect_rwd_wire_capture,
    iter_rwd_wire_chunks,
)
from .client import RWDClientDiagnostics, RWDRecordSource, RWDStreamClient
from .domain import (
    RWDEventRecord,
    RWDFluorescenceRecord,
    RWDFluorescenceSample,
    RWDReceivedRecord,
    RWDRecord,
    RWDSessionData,
    RWDStreamMetadata,
    RWDWavelength,
)
from .protocol import (
    EVENT_RECORD_BYTES,
    FLUORESCENCE_RECORD_BYTES,
    RWD_PROTOCOL_VERSION,
    RWDDecoderDiagnostics,
    RWDProtocolError,
    RWDStreamDecoder,
    parse_event_record,
    parse_fluorescence_record,
)
from .timing import (
    RWDClockDiscontinuity,
    RWDNormalizedEvent,
    RWDNormalizedRecord,
    RWDNormalizedSample,
    RWDNormalizedSession,
    RWDTickResolver,
    normalize_rwd_session,
)

__all__ = [
    "EVENT_RECORD_BYTES",
    "FLUORESCENCE_RECORD_BYTES",
    "RWD_PROTOCOL_VERSION",
    "RWDClientDiagnostics",
    "RWDClockDiscontinuity",
    "RWDDecoderDiagnostics",
    "RWDEventRecord",
    "RWDFluorescenceRecord",
    "RWDFluorescenceSample",
    "RWDNormalizedEvent",
    "RWDNormalizedRecord",
    "RWDNormalizedSample",
    "RWDNormalizedSession",
    "RWDProtocolError",
    "RWDReceivedRecord",
    "RWDRecord",
    "RWDRecordSource",
    "RWDSessionData",
    "RWDStreamClient",
    "RWDStreamDecoder",
    "RWDStreamMetadata",
    "RWDTickResolver",
    "RWDWavelength",
    "RWDWireCaptureError",
    "RWDWireCaptureInspection",
    "RWDWireCaptureWriter",
    "RWDWireChunk",
    "RWDWireReplaySource",
    "inspect_rwd_wire_capture",
    "iter_rwd_wire_chunks",
    "normalize_rwd_session",
    "parse_event_record",
    "parse_fluorescence_record",
]
